### ISSUE TITLE
dump function and debugger in profile becomes unavailable

### ISSUE THREAD

**Issue by zeckon** [PandawanTechnology/Neo4jBundle#2]
Thanks for the bundle, but I have a small small issue.

when I get a client and do some match, i get the results (i can see in profiler) but dump function stops working (no output to debug bar or in profiler/debug)

for ex.

$client = $this->get('pandawan_technology_neo4j.client');
$result = $client->run("MATCH (n:Person) RETURN n");
dump("test"); // doesnt give any output

If i use the client directly from GraphAware it works

ClientBuilder::create()->addConnection('........')->build();
$result = $client->run("MATCH (n:Person) RETURN n");
dump("test"); // this gives output

After doing some tests i suspect this may be related to event dispatcher class being passed to Graphaware  Client in ConnectionCompilerPass.php 

in line 47, when i change

$eventDispatcher = $container->findDefinition('event_dispatcher');

with

$eventDispatcher = $container->findDefinition('debug.event_dispatcher.parent');

or if i just set it to null dump outputs are back (but this time neo4j section in profiler doesn't measure anything although i get the results, probably neo4j profiler events are not dispatching)

Thanks for any help

**Comment by zeckon** [comment]
$client = $this->get('pandawan_technology_neo4j.client');
$result = $client->run("MATCH (n:Person) RETURN n");
var_dump($result); 

when i run this, i get the results such as

object(GraphAware\Bolt\Result\Result)[379]
  protected 'records' => 
    array (size=133)
      0 => 
        object(GraphAware\Bolt\Record\RecordView)[651]
          protected 'keys' => 
            array (size=1)
              ...
          protected 'values' => 
            array (size=1)
              ...
          private 'keyToIndexMap' => 
            array (size=1)
              ...
      1 => 
        object(GraphAware\Bolt\Record\RecordView)[653]
          protected 'keys' => 
            array (size=1)
              ...
          protected 'values' => 
            array (size=1)
              ...
          private 'keyToIndexMap' => 
            array (size=1)
              ...

 but still dumps are not giving any output to debugger. I suspect maybe it overrides debugger events?

**Comment by xavismeh** [comment]
This issue has been fixed into https://github.com/neo4j-contrib/neo4j-symfony. Please use this one instead as Pandawan Technology version will not be maintained anymore
